services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - auth-service

  book-service:
    build: ./book-service
    ports:
      - "8001:8001"
    networks:
      - app-network

  admin-service:
    build: ./admin-service
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - user-service
      - book-service

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - auth-service
      - user-service
      - book-service
      - admin-service

networks:
  app-network:
    driver: bridge

